# Site settings
title:            De maand van Adriaan
description:      "Volg hier de blog waarin Adriaan elke maand iets uit gaat proberen. Walg, geniet, verbaas!"
baseurl:          ""


logo:             site-logo.png
disqus_shortname: demaandvanadriaan
search:           false
# Change url to your domain. Leave localhost server or blank when working locally.
# You don't need to specify the protocol if you want it available on http and https. Example: //localhost:4000
url:              "http://demaandvanadriaan.nl"

# Owner/author information
owner:
  name:           Adriaan
  avatar:         bio-photo.jpg
  email:          reacties@demaandvanadriaan.nl
  # Social networking links used in footer. Update and remove as you like.
  twitter:        maandvanadriaan
  facebook:       demaandvanadriaan
  github:         harianus/demaandvanadriaan
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:    https://plus.google.com/u/0/b/100727344084502034047

# Analytics and webmaster tools stuff goes here
google_analytics: UA-243569-34
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  # - title: Water
  #   url: /water/
  # - title: Posts
  #   url: /posts/
  # - title: Made Mistakes
  #   url: http://mademistakes.com
  #   external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Amsterdam
language:    nl
future:      true
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "README.md", "LICENSE", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
